// Regenerates ../ui-icons.js: scans the editor sources for Lucide icon names and bundles just those.
// Usage (from artifacts/easel): node tools/build-icons.mjs
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';

const src = readdirSync('.').filter(f => f.endsWith('.js') && f !== 'ui-icons.js').map(f => readFileSync(f, 'utf8')).join('\n')
  + readFileSync('../easel.html', 'utf8');
const names = new Set();
const patterns = [
  /\bicon\('([a-z0-9-]+)'/g, /\bcb\('([a-z0-9-]+)'/g, /data-ic="([a-z0-9-]+)"/g,
  /\bic: '([a-z0-9-]+)'/g, /\bicon: '([a-z0-9-]+)'/g, /'([a-z0-9-]+)'\s*:\s*'[a-z0-9-]+'/g,
  /\[\s*'(align-[a-z0-9-]+|chart-[a-z]+)'/g, /\['[^']*', '[^']*', '([a-z0-9-]+)'\]/g,
];
for (const re of patterns) for (const m of src.matchAll(re)) names.add(m[1]);
// names chosen at runtime (ternaries / maps) that the patterns above can't see
['text-align-start', 'text-align-center', 'text-align-end', 'text-align-justify', 'lock-open', 'eye', 'eye-off',
  'arrow-left', 'arrow-right', 'circle', 'mouse-pointer-2', 'pen-tool', 'chart-column', 'move-horizontal', 'frame',
  'sparkles', 'qr-code', 'group', 'square', 'type', 'image', 'trash-2'].forEach(n => names.add(n));

const res = await fetch('https://cdn.jsdelivr.net/npm/@iconify-json/lucide@1/icons.json');
const set = await res.json();
const out = {}, missing = [];
for (const n of [...names].sort()) {
  let ic = set.icons[n];
  if (!ic && set.aliases?.[n]) ic = set.icons[set.aliases[n].parent];
  if (ic) out[n] = ic.body; else missing.push(n);
}
const W = set.width || 24, H = set.height || 24;
writeFileSync('ui-icons.js', `/* Easel — UI icons: a subset of Lucide (ISC licence, lucide.dev), bundled so the interface needs no icon requests.
   Generated by tools/build-icons.mjs — do not edit by hand. */
window.EZ = window.EZ || {};
EZ.UI_ICONS = { size: [${W}, ${H}], icons: ${JSON.stringify(out)} };
`);
console.log(`${Object.keys(out).length} icons written; not Lucide names (ignored): ${missing.join(', ') || 'none'}`);
